DEBUG 2025-04-10 09:59:23.855 UTC: 	 CRAB Client version: v3.250318
DEBUG 2025-04-10 09:59:23.855 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-04-10 09:59:23.855 UTC: 	 Not using Singularity
DEBUG 2025-04-10 09:59:23.855 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-04-10 09:59:23.855 UTC: 	 Executing command: 'submit'
DEBUG 2025-04-10 09:59:23.856 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
ERROR 2025-04-10 09:59:23.856 UTC: 	 CRAB configuration file crabConfig.py not found.
ERROR 2025-04-10 09:59:23.857 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
CRABClient.ClientExceptions.ConfigurationException: CRAB configuration file crabConfig.py not found.
INFO 2025-04-10 09:59:23.860 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab.log
DEBUG 2025-04-10 10:26:59.542 UTC: 	 CRAB Client version: v3.250318
DEBUG 2025-04-10 10:26:59.542 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-04-10 10:26:59.542 UTC: 	 Not using Singularity
DEBUG 2025-04-10 10:26:59.542 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-04-10 10:26:59.542 UTC: 	 Executing command: 'submit'
DEBUG 2025-04-10 10:26:59.542 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-04-10 10:26:59.543 UTC: 	 Will use CRAB configuration file crab_NuE10_DIGI_PU_Phase2.py
DEBUG 2025-04-10 10:26:59.543 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-04-10 10:26:59.545 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-04-10 10:26:59.546 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_GEN-SIM-DIGI-RAW' already exists 
Please change the requestName in the config file
ERROR 2025-04-10 10:26:59.546 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_GEN-SIM-DIGI-RAW' already exists 
Please change the requestName in the config file
INFO 2025-04-10 10:26:59.550 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab.log
DEBUG 2025-04-11 08:05:48.027 UTC: 	 CRAB Client version: v3.250318
DEBUG 2025-04-11 08:05:48.028 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-04-11 08:05:48.028 UTC: 	 Not using Singularity
DEBUG 2025-04-11 08:05:48.028 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-04-11 08:05:48.028 UTC: 	 Executing command: 'submit'
DEBUG 2025-04-11 08:05:48.028 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-04-11 08:05:48.029 UTC: 	 Will use CRAB configuration file crab_NuE10_DIGI_PU_Phase2.py
DEBUG 2025-04-11 08:05:48.029 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-04-11 08:05:48.036 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-04-11 08:05:48.036 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_GEN-SIM-DIGI-RAW' already exists 
Please change the requestName in the config file
ERROR 2025-04-11 08:05:48.036 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_GEN-SIM-DIGI-RAW' already exists 
Please change the requestName in the config file
INFO 2025-04-11 08:05:48.048 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab.log
DEBUG 2025-04-12 19:31:31.724 UTC: 	 CRAB Client version: v3.250318
DEBUG 2025-04-12 19:31:31.725 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-04-12 19:31:31.725 UTC: 	 Not using Singularity
DEBUG 2025-04-12 19:31:31.725 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-04-12 19:31:31.725 UTC: 	 Executing command: 'submit'
DEBUG 2025-04-12 19:31:31.726 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-04-12 19:31:31.727 UTC: 	 Will use CRAB configuration file crab_NuE10_DIGI_PU_Phase2.py
DEBUG 2025-04-12 19:31:31.727 UTC: 	 Loading CRAB configuration file.
ERROR 2025-04-12 19:31:31.732 UTC: 	 Invalid CRAB configuration: Parameter Data.unitsPerJob is mandatory for 'EventAwareLumiBased' splitting mode.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2025-04-12 19:31:31.733 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/SubCommand.py", line 95, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Invalid CRAB configuration: Parameter Data.unitsPerJob is mandatory for 'EventAwareLumiBased' splitting mode.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2025-04-12 19:31:31.756 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab.log
DEBUG 2025-04-15 18:27:28.090 UTC: 	 CRAB Client version: v3.250318
DEBUG 2025-04-15 18:27:28.090 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-04-15 18:27:28.090 UTC: 	 Not using Singularity
DEBUG 2025-04-15 18:27:28.090 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-04-15 18:27:28.090 UTC: 	 Executing command: 'submit'
DEBUG 2025-04-15 18:27:28.091 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-04-15 18:27:28.092 UTC: 	 Will use CRAB configuration file crab_NuE10_Phase2_step2_cfg.py
DEBUG 2025-04-15 18:27:28.092 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-04-15 18:27:28.096 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-04-15 18:27:28.096 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_MINIAOD' already exists 
Please change the requestName in the config file
ERROR 2025-04-15 18:27:28.096 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_MINIAOD' already exists 
Please change the requestName in the config file
INFO 2025-04-15 18:27:28.113 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab.log
DEBUG 2025-04-16 16:00:08.266 UTC: 	 CRAB Client version: v3.250318
DEBUG 2025-04-16 16:00:08.267 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-04-16 16:00:08.267 UTC: 	 Not using Singularity
DEBUG 2025-04-16 16:00:08.267 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-04-16 16:00:08.267 UTC: 	 Executing command: 'submit'
DEBUG 2025-04-16 16:00:08.268 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-04-16 16:00:08.270 UTC: 	 Will use CRAB configuration file crab_NuE10_Phase2_step2_cfg.py
DEBUG 2025-04-16 16:00:08.270 UTC: 	 Loading CRAB configuration file.
ERROR 2025-04-16 16:00:08.278 UTC: 	 Invalid CRAB configuration: In case of Automatic splitting, the Data.unitsPerJob parameter must be in the [180, 2700] minutes range. You asked for 1 minutes.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2025-04-16 16:00:08.278 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/SubCommand.py", line 95, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Invalid CRAB configuration: In case of Automatic splitting, the Data.unitsPerJob parameter must be in the [180, 2700] minutes range. You asked for 1 minutes.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2025-04-16 16:00:08.316 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab.log
DEBUG 2025-05-23 20:58:06.855 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-23 20:58:06.855 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-23 20:58:06.855 UTC: 	 Not using Singularity
DEBUG 2025-05-23 20:58:06.855 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-05-23 20:58:06.855 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-23 20:58:06.855 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-05-23 20:58:06.857 UTC: 	 Will use CRAB configuration file crab_NuE10_Phase2_step2_cfg.py
DEBUG 2025-05-23 20:58:06.857 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-05-23 20:58:06.859 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-05-23 20:58:06.860 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_MINIAOD_gemsegm' already exists 
Please change the requestName in the config file
ERROR 2025-05-23 20:58:06.860 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_MINIAOD_gemsegm' already exists 
Please change the requestName in the config file
INFO 2025-05-23 20:58:06.888 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab.log
DEBUG 2025-05-28 11:51:34.109 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-28 11:51:34.109 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-28 11:51:34.109 UTC: 	 Not using Singularity
DEBUG 2025-05-28 11:51:34.109 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-05-28 11:51:34.109 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-28 11:51:34.110 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-05-28 11:51:34.110 UTC: 	 Will use CRAB configuration file crab_NuE10_Phase2_step2_cfg.py
DEBUG 2025-05-28 11:51:34.110 UTC: 	 Loading CRAB configuration file.
ERROR 2025-05-28 11:51:34.118 UTC: 	 Error while loading CRAB configuration:
[Errno 2] No such file or directory: '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/file_.txt'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2025-05-28 11:51:34.118 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_NuE10_Phase2_step2_cfg.py", line 12, in <module>
    config.Data.userInputFiles = open('/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/file_.txt').readlines()
FileNotFoundError: [Errno 2] No such file or directory: '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/file_.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 56, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/WMCore/Configuration.py", line 346, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_NuE10_Phase2_step2_cfg.py
Due to error:
[Errno 2] No such file or directory: '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/file_.txt'Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_NuE10_Phase2_step2_cfg.py", line 12, in <module>
    config.Data.userInputFiles = open('/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/file_.txt').readlines()
FileNotFoundError: [Errno 2] No such file or directory: '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/file_.txt'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 90, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
[Errno 2] No such file or directory: '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/file_.txt'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2025-05-28 11:51:34.144 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab.log
DEBUG 2025-05-28 11:52:01.699 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-28 11:52:01.699 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-28 11:52:01.699 UTC: 	 Not using Singularity
DEBUG 2025-05-28 11:52:01.699 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-05-28 11:52:01.699 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-28 11:52:01.699 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-05-28 11:52:01.700 UTC: 	 Will use CRAB configuration file crab_NuE10_Phase2_step2_cfg.py
DEBUG 2025-05-28 11:52:01.700 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-05-28 11:52:01.718 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-05-28 11:52:01.718 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_MINIAOD_gemsegm_match' already exists 
Please change the requestName in the config file
ERROR 2025-05-28 11:52:01.718 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_MINIAOD_gemsegm_match' already exists 
Please change the requestName in the config file
INFO 2025-05-28 11:52:01.723 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab.log
DEBUG 2025-05-28 11:53:29.006 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-28 11:53:29.006 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-28 11:53:29.006 UTC: 	 Not using Singularity
DEBUG 2025-05-28 11:53:29.006 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-05-28 11:53:29.006 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-28 11:53:29.006 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-05-28 11:53:29.007 UTC: 	 Will use CRAB configuration file crab_NuE10_Phase2_step2_cfg.py
DEBUG 2025-05-28 11:53:29.007 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-05-28 11:53:29.011 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-05-28 11:53:29.011 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_MINIAOD_gemsegm_match' already exists 
Please change the requestName in the config file
ERROR 2025-05-28 11:53:29.011 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_MINIAOD_gemsegm_match' already exists 
Please change the requestName in the config file
INFO 2025-05-28 11:53:29.014 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab.log
DEBUG 2025-05-28 11:54:23.044 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-28 11:54:23.044 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-28 11:54:23.044 UTC: 	 Not using Singularity
DEBUG 2025-05-28 11:54:23.044 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-05-28 11:54:23.044 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-28 11:54:23.044 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-05-28 11:54:23.045 UTC: 	 Will use CRAB configuration file crab_NuE10_Phase2_step2_cfg.py
DEBUG 2025-05-28 11:54:23.045 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-05-28 11:54:23.050 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-05-28 11:54:23.050 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_MINIAOD_gemsegm_match' already exists 
Please change the requestName in the config file
ERROR 2025-05-28 11:54:23.050 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_MINIAOD_gemsegm_match' already exists 
Please change the requestName in the config file
INFO 2025-05-28 11:54:23.064 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab.log
DEBUG 2025-06-02 22:30:30.253 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-06-02 22:30:30.253 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-06-02 22:30:30.253 UTC: 	 Not using Singularity
DEBUG 2025-06-02 22:30:30.253 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-06-02 22:30:30.253 UTC: 	 Executing command: 'submit'
DEBUG 2025-06-02 22:30:30.254 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-06-02 22:30:30.255 UTC: 	 Will use CRAB configuration file crab_NuE10_DIGI_PU50_Phase2.py
DEBUG 2025-06-02 22:30:30.255 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-06-02 22:30:30.257 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-06-02 22:30:30.257 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_GEN-SIM-DIGI-RAW_PU50' already exists 
Please change the requestName in the config file
ERROR 2025-06-02 22:30:30.257 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_GEN-SIM-DIGI-RAW_PU50' already exists 
Please change the requestName in the config file
INFO 2025-06-02 22:30:30.307 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab.log
DEBUG 2025-06-03 12:17:48.787 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-06-03 12:17:48.787 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-06-03 12:17:48.787 UTC: 	 Not using Singularity
DEBUG 2025-06-03 12:17:48.787 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-06-03 12:17:48.787 UTC: 	 Executing command: 'submit'
DEBUG 2025-06-03 12:17:48.787 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-06-03 12:17:48.788 UTC: 	 Will use CRAB configuration file crab_NuE10_Phase2_step2_cfg_PU50.py
DEBUG 2025-06-03 12:17:48.788 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-06-03 12:17:48.790 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-06-03 12:17:48.792 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_MINIAOD_PU50' already exists 
Please change the requestName in the config file
ERROR 2025-06-03 12:17:48.792 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_MINIAOD_PU50' already exists 
Please change the requestName in the config file
INFO 2025-06-03 12:17:48.818 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab.log
ERROR 2025-06-04 06:54:04.927 UTC: 	 Keyboard Interrupted
INFO 2025-06-04 06:54:04.947 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab.log
DEBUG 2025-06-04 20:22:22.348 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-06-04 20:22:22.348 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-06-04 20:22:22.348 UTC: 	 Not using Singularity
DEBUG 2025-06-04 20:22:22.348 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-06-04 20:22:22.348 UTC: 	 Executing command: 'submit'
DEBUG 2025-06-04 20:22:22.348 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-06-04 20:22:22.349 UTC: 	 Will use CRAB configuration file NuGunE10_step3_MiniAOD_PU50.py
DEBUG 2025-06-04 20:22:22.349 UTC: 	 Loading CRAB configuration file.
ERROR 2025-06-04 20:23:31.769 UTC: 	 Error while loading CRAB configuration:
Unable to find a Configuration object instance in file:
/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/NuGunE10_step3_MiniAOD_PU50.py

Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2025-06-04 20:23:31.769 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 56, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/WMCore/Configuration.py", line 354, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to find a Configuration object instance in file:
/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/NuGunE10_step3_MiniAOD_PU50.py


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 90, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
Unable to find a Configuration object instance in file:
/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/NuGunE10_step3_MiniAOD_PU50.py

Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2025-06-04 20:23:31.790 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab.log
DEBUG 2025-06-05 06:59:05.096 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-06-05 06:59:05.096 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-06-05 06:59:05.096 UTC: 	 Not using Singularity
DEBUG 2025-06-05 06:59:05.096 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-06-05 06:59:05.096 UTC: 	 Executing command: 'status'
DEBUG 2025-06-05 06:59:05.096 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
ERROR 2025-06-05 06:59:05.097 UTC: 	 Cannot find .requestcache file in CRAB project directory /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_MINIAOD_PU140_v2
ERROR 2025-06-05 06:59:05.097 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 695, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 537, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 531, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_MINIAOD_PU140_v2
INFO 2025-06-05 06:59:05.119 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab.log
DEBUG 2025-06-05 07:03:32.500 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-06-05 07:03:32.501 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-06-05 07:03:32.501 UTC: 	 Not using Singularity
DEBUG 2025-06-05 07:03:32.501 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-06-05 07:03:32.501 UTC: 	 Executing command: 'status'
DEBUG 2025-06-05 07:03:32.501 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
ERROR 2025-06-05 07:03:32.502 UTC: 	 Cannot find .requestcache file in CRAB project directory /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_MINIAOD_PU140_v2
ERROR 2025-06-05 07:03:32.502 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 695, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 537, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 531, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab_projects/crab_140X_mcPhase2_14TeV_NuGun_MINIAOD_PU140_v2
INFO 2025-06-05 07:03:32.505 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/MC_generation/NuGun/CrabSubmission/crab.log
